#version: '3.8'
#services:
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "9192:9192"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/projectmanagement?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - app-network
#
#  db:
#    image: mysql:8.0
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=projectmanagement
#    ports:
#      - "3306:3306"
#    volumes:
#      - db-data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      retries: 5
#      timeout: 5s
#    networks:
#      - app-network
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "5173:5173"
#    environment:
#      - VITE_API_URL=http://backend:9192
#    depends_on:
#      - backend
#    networks:
#      - app-network
#
#volumes:
#  db-data:
#
#networks:
#  app-network:
#    driver: bridge

version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9192:9192"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/projectmanagement?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:9192
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge